# See https://github.com/silverstripe/silverstripe-travis-support for setup details

language: php

sudo: false

matrix:
  include:
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3
    - php: 7.0
      env: DB=MYSQL CORE_RELEASE=3
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3

before_script:
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
 - vendor/bin/phpunit controllerpolicy/tests/
