mappings:
  ControllerPolicyApplicator: SilverStripe\ControllerPolicy\ControllerPolicyApplicator
  ControllerPolicy: SilverStripe\ControllerPolicy\ControllerPolicy
  PageControlledPolicy: SilverStripe\ControllerPolicy\PageControlledPolicy
  ControllerPolicyRequestFilter: SilverStripe\ControllerPolicy\ControllerPolicyMiddleware
  CachingPolicy: SilverStripe\ControllerPolicy\Policies\CachingPolicy
  CustomHeaderPolicy: SilverStripe\ControllerPolicy\Policies\CustomHeaderPolicy
