---
Name: controllerpolicy
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\RequestProcessor:
    properties:
      filters:
        - '%$SilverStripe\ControllerPolicy\ControllerPolicyRequestFilter'

SilverStripe\ControllerPolicy\ControllerPolicyApplicator:
  dependencies:
    RequestFilter: '%$SilverStripe\ControllerPolicy\ControllerPolicyRequestFilter'

SilverStripe\Control\Controller:
  extensions:
    - SilverStripe\ControllerPolicy\ControllerPolicyApplicator
