---
Name: controllerpolicy
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        ControllerPolicyMiddleware: '%$SilverStripe\ControllerPolicy\ControllerPolicyMiddleware'

  # Use a non-singleton pattern, since each extension will contain policies unique per controller
  SilverStripe\ControllerPolicy\ControllerPolicyApplicator:
    type: prototype

SilverStripe\ControllerPolicy\ControllerPolicyApplicator:
  dependencies:
    Middleware: '%$SilverStripe\ControllerPolicy\ControllerPolicyMiddleware'

SilverStripe\Control\Controller:
  extensions:
    - SilverStripe\ControllerPolicy\ControllerPolicyApplicator
